version: '3.9'

services:
  database:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretp@ssw0rd
      POSTGRES_USER: smUser
      POSTGRES_DB: mysm-db
    restart: unless-stopped   
volumes:
  postgres_data:
